### ISSUE TITLE
Yahtzee Run Error

### ISSUE THREAD

**Issue by OregonFanBoy** [spencerk80/CasinoSuite#3]
Expected result:
**********************
***  Test roll   ****
*********************
Enter number of dice to roll:

Actual result:
Process finished with exit code 0

![yahtzee run error](https://cloud.githubusercontent.com/assets/16273836/11800113/adffec02-a28e-11e5-92ac-6ee872388f96.PNG)

**Comment by spencerk80** [comment]
It's to be run from another source because it's not a stand-alone class. Easiest way to test:
Open python interpreter from the directory.
Enter:
from Yahtzee import Yahtzee
game = Yahtzee(None)
game.run()

**Comment by OregonFanBoy** [comment]
I added the code you listed to MainMenu.py
Problem now solved. I'll be sure to keep this for when user selects to play
Yahtzee.
Good work!
