### ISSUE TITLE
QUESTION: Symbols for slot machine

### ISSUE THREAD

**Issue by OregonFanBoy** [spencerk80/CasinoSuite#6]
I would like to know what symbols we want to use in the slot machine and the value worth of the symbol.

**Comment by spencerk80** [comment]
cherry plum bell clover lemon coin bar apple heart grape diamond orange horse-shoe 7 '?' or watermelon to be a few lol

**Comment by spencerk80** [comment]
Cherries always pay out. 1, 2 or 3 all pay, differently. The more cherries, the more money won.

7: Must have full row

Bar: ditto

Maybe one of the other fruits can be 2 or 3 and payout

**Comment by OregonFanBoy** [comment]
I still have some math to work out for the slot machine. Right now I will be using 3 columns. There is 1 reel per column. Each reel will generate a random number. These 3 random numbers will be stored and then I will divide each number by 64 and keep the remainder value. This will be called VirtualReel. Since I am only keeping the remainder value, the vitrualReel should only be in the range of 1 to 64. The VirtualReel will be the selector to tell the real to stop at a certian number. The Table below will provide an example of how this works. However based on the table, Each symbol has a 12.5% chance of being landed on. This means if we were to line up three symbols, thats 1 in 64^3 thus landing 3 symbols in a row has the odds of 0.00038%
[SlotMachineTable.xlsx](https://github.com/spencerk80/CasinoSuite/files/66164/SlotMachineTable.xlsx)

**Comment by spencerk80** [comment]
Okay. Sounds interesting
