### ISSUE TITLE
BUG...ISH: Main Menu has code at the bottom it shouldn't have

### ISSUE THREAD

**Issue by spencerk80** [spencerk80/CasinoSuite#9]
The Play.py works fine for running the Main Menu, you can remove the code at the bottom and simply run:
python Play.py

**Comment by OregonFanBoy** [comment]
run function from MainMenu class has now been adjusted to be called from the Play class. Should see the change on my next push.

**Comment by spencerk80** [comment]
Move the declarations to the class lvl so that they are part of the class.

**Comment by OregonFanBoy** [comment]
Class declarations have been moved to class level now.
